name: greengrocers
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  fluro: ^1.6.3
  hexcolor: ^1.0.4
  flutter_svg: ^0.19.1
  google_maps_flutter: ^1.0.2
  flutter_google_places: ^0.2.6
  simple_animations: ^2.2.3
  location: ^3.0.2
  carousel_pro: ^0.0.13
  bubble_bottom_bar: ^1.2.0
  google_maps_webservice: ^0.0.18
  geocoder: ^0.2.1
  cloud_firestore: ^0.14.0+2
  geolocator: ^6.0.0+4
  http: ^0.12.2
  firebase_auth: ^0.18.1+1
  google_sign_in: ^4.5.4
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.1
  razorpay_flutter: ^1.2.2
  fluttertoast: ^7.1.1
  shared_preferences: ^0.5.12
  image_picker: ^0.6.7+11
  cached_network_image: ^2.3.2+1
  google_fonts: ^1.1.0
  carousel_slider: ^2.3.1
  intl: ^0.16.1
  uuid: ^2.2.2
  provider: ^4.3.2+2
  flutter_spinkit: ^4.1.2+1
  transparent_image: ^1.0.0
  flutter_search_panel: ^1.0.1
  flutter_typeahead: ^1.8.8
  modal_progress_hud: ^0.1.3
  flutter_signin_button: ^1.1.0
  flutter_credit_card: ^0.1.3
  stripe_payment: ^1.0.9
  progress_dialog: ^1.2.2
  awesome_dialog: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Dosis
      fonts:
        - asset: fonts/Dosis/Dosis-Regular.ttf
          weight: 400
        - asset: fonts/Dosis/Dosis-Medium.ttf
          weight: 500
        - asset: fonts/Dosis/Dosis-SemiBold.ttf
          weight: 600
        - asset: fonts/Dosis/Dosis-Bold.ttf
          weight: 800
        - asset: fonts/Dosis/Dosis-ExtraBold.ttf
          weight: 900

    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
